---
Parameters:

  Prefix:
    Type: String
    Description: Prefix name that joins all the stacks

Resources:

  GreenColorTellerService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue:
          !Sub '${Prefix}:Cluster'
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 1
      LaunchType: 'FARGATE'
      ServiceRegistries:
        - RegistryArn:
            Fn::ImportValue:
              !Sub "${Prefix}:ColorTellerServiceRegistryArn"
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Sub "${Prefix}:SecurityGroup"
          Subnets:
            - Fn::ImportValue:
                !Sub '${Prefix}-vpc:PrivateSubnet1'
            - Fn::ImportValue:
                !Sub '${Prefix}-vpc:PrivateSubnet2'
      TaskDefinition: !Ref GreenColorTellerTaskDefinition

  GreenColorTellerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - 'FARGATE'
      Family: 'green'
      NetworkMode: 'awsvpc'
      Cpu: 512
      Memory: 1024
      TaskRoleArn:
        Fn::ImportValue:
          !Sub "${Prefix}:TaskIamRole"
      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub "${Prefix}:TaskExecutionIamRole"
      ContainerDefinitions:
        - Name: 'app'
          Image: subfuzion/colorteller
          Essential: true
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Sub ${Prefix}-log-group
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'green'
          PortMappings:
            - ContainerPort: 9080
              Protocol: 'tcp'
          Environment:
            - Name: "SERVER_PORT"
              Value: "9080"
            - Name: "COLOR"
              Value: "green"
            - Name: "STAGE"
              Value: ""

